# **Numpy**

In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
import sys
sys.version

'3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]'

In [4]:
# create a list

my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
# how to convert list to array
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [11]:
np.arange(5,100, 10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [12]:
np.arange(20,10)

array([], dtype=int64)

In [13]:
np.arange(-20,10)


array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [14]:
np.zeros(5) # this is called parameter concept

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5, dtype=int) # this is called hyper parameter tunning

array([0, 0, 0, 0, 0])

# 2D **array**

In [16]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.zeros((10,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
# np.three(2)

In [23]:
np.random.rand(2)

array([0.96266373, 0.70210179])

In [24]:
np.random.rand(2,3)

array([[0.64127575, 0.99672229, 0.29513897],
       [0.30466204, 0.93964056, 0.97479364]])

In [25]:
np.random.randint(2)

0

In [26]:
np.random.randint(2,9)

5

In [27]:
np.random.randint(2,9,4) # generate random integar 4 number

array([6, 4, 6, 2])

In [28]:
import numpy as np

otp = np.random.randint(1000, 10000)

print("Your OTP is:", otp)

Your OTP is: 5958


In [29]:
np.random.randint(10,40,(10,10))

array([[27, 19, 24, 31, 11, 15, 12, 20, 13, 18],
       [22, 17, 34, 28, 25, 12, 14, 29, 20, 28],
       [14, 14, 19, 24, 31, 17, 11, 18, 25, 36],
       [29, 27, 34, 13, 29, 10, 35, 21, 14, 32],
       [16, 30, 18, 13, 33, 33, 18, 20, 18, 28],
       [29, 20, 37, 28, 17, 15, 18, 13, 27, 34],
       [18, 37, 25, 28, 26, 34, 14, 32, 24, 20],
       [20, 33, 32, 23, 22, 22, 22, 38, 18, 35],
       [38, 13, 35, 18, 20, 30, 13, 11, 36, 35],
       [27, 16, 21, 18, 39, 38, 27, 16, 32, 16]])

In [30]:
arr = np.random.randint(10,40,(10,10))
print(arr)

[[26 19 28 39 31 25 26 26 29 24]
 [36 36 18 17 13 22 32 12 13 33]
 [32 12 33 14 26 38 33 25 28 35]
 [25 22 18 19 10 34 22 32 12 34]
 [31 37 10 36 32 21 34 17 31 36]
 [29 17 37 35 36 25 20 31 29 10]
 [10 31 29 35 11 37 18 21 19 36]
 [19 19 30 12 13 34 24 30 31 17]
 [39 26 34 29 31 19 32 34 25 37]
 [34 37 11 36 19 38 37 39 35 38]]


In [31]:
arr[5]

array([29, 17, 37, 35, 36, 25, 20, 31, 29, 10])

In [32]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [34]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [36]:
np.random.randint(2,20,4) # 2nd argument is exlusive

array([19, 16, 19, 16])

In [37]:
np.random.randint(1,10,3) # 1 se 10 ka 3 random value

array([1, 5, 4])

In [38]:
np.random.randint(5,9) #GET THE VALUE <=1 & >=5

5

In [39]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
np.arange(1,15).reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

# *slicing in matrix*

In [42]:
b = np.random.randint(10,20,(5,4)) # 10 se 20 tak ka random value 5*4 matrix 5 row and 4 column
b

array([[10, 14, 14, 13],
       [13, 10, 12, 12],
       [11, 15, 11, 13],
       [11, 12, 18, 11],
       [14, 16, 17, 11]])

In [43]:
type(b)

numpy.ndarray

In [44]:
b[:]

array([[10, 14, 14, 13],
       [13, 10, 12, 12],
       [11, 15, 11, 13],
       [11, 12, 18, 11],
       [14, 16, 17, 11]])

In [45]:
b[3:]

array([[11, 12, 18, 11],
       [14, 16, 17, 11]])

In [46]:
b[:3]

array([[10, 14, 14, 13],
       [13, 10, 12, 12],
       [11, 15, 11, 13]])

In [47]:
b[::2]  # start se end tak jumn of 2

array([[10, 14, 14, 13],
       [11, 15, 11, 13],
       [14, 16, 17, 11]])

In [48]:
b[1:3]

array([[13, 10, 12, 12],
       [11, 15, 11, 13]])

In [49]:
b[1,2]

np.int64(12)

In [50]:
b

array([[10, 14, 14, 13],
       [13, 10, 12, 12],
       [11, 15, 11, 13],
       [11, 12, 18, 11],
       [14, 16, 17, 11]])

In [51]:
b[1,-1]

np.int64(12)

In [52]:
b[0:-2]

array([[10, 14, 14, 13],
       [13, 10, 12, 12],
       [11, 15, 11, 13]])

In [53]:
b[-5:-3]

array([[10, 14, 14, 13],
       [13, 10, 12, 12]])

# **Operations**

In [54]:
a = np.random.randint(10,20,10)
a

array([10, 14, 10, 18, 19, 11, 17, 10, 17, 14])

In [55]:
id(a)

135476214361488

In [56]:
arr

array([[26, 19, 28, 39, 31, 25, 26, 26, 29, 24],
       [36, 36, 18, 17, 13, 22, 32, 12, 13, 33],
       [32, 12, 33, 14, 26, 38, 33, 25, 28, 35],
       [25, 22, 18, 19, 10, 34, 22, 32, 12, 34],
       [31, 37, 10, 36, 32, 21, 34, 17, 31, 36],
       [29, 17, 37, 35, 36, 25, 20, 31, 29, 10],
       [10, 31, 29, 35, 11, 37, 18, 21, 19, 36],
       [19, 19, 30, 12, 13, 34, 24, 30, 31, 17],
       [39, 26, 34, 29, 31, 19, 32, 34, 25, 37],
       [34, 37, 11, 36, 19, 38, 37, 39, 35, 38]])

In [57]:
arr2 = np.random.randint(0,100,(10,10))

In [58]:
arr2

array([[86, 98, 96, 64, 63, 96, 33, 76, 96, 31],
       [79, 31, 41, 43, 65, 39, 20, 39, 14, 97],
       [36, 76, 60, 50, 28, 39, 38, 22,  8, 41],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43],
       [ 3, 83, 38, 80, 76, 78, 49, 70, 28, 24],
       [80, 15, 98, 98, 35, 62, 62, 58, 83, 31],
       [51, 45, 39,  2, 94, 85, 34, 23, 24, 30],
       [32, 47, 87, 62, 19, 17,  6, 33, 99, 34],
       [95, 63, 70,  8, 59, 18,  0, 11,  3, 61],
       [68, 87,  6,  3, 15, 61,  1, 46,  0, 50]])

In [59]:
arr2[:
     ]

array([[86, 98, 96, 64, 63, 96, 33, 76, 96, 31],
       [79, 31, 41, 43, 65, 39, 20, 39, 14, 97],
       [36, 76, 60, 50, 28, 39, 38, 22,  8, 41],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43],
       [ 3, 83, 38, 80, 76, 78, 49, 70, 28, 24],
       [80, 15, 98, 98, 35, 62, 62, 58, 83, 31],
       [51, 45, 39,  2, 94, 85, 34, 23, 24, 30],
       [32, 47, 87, 62, 19, 17,  6, 33, 99, 34],
       [95, 63, 70,  8, 59, 18,  0, 11,  3, 61],
       [68, 87,  6,  3, 15, 61,  1, 46,  0, 50]])

In [60]:
arr2[2:4]

array([[36, 76, 60, 50, 28, 39, 38, 22,  8, 41],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43]])

In [61]:
arr2[1,4]

np.int64(65)

In [62]:
arr2[-5,-5]

np.int64(62)

In [63]:
arr2[-1,-2]

np.int64(0)

In [64]:
arr2

array([[86, 98, 96, 64, 63, 96, 33, 76, 96, 31],
       [79, 31, 41, 43, 65, 39, 20, 39, 14, 97],
       [36, 76, 60, 50, 28, 39, 38, 22,  8, 41],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43],
       [ 3, 83, 38, 80, 76, 78, 49, 70, 28, 24],
       [80, 15, 98, 98, 35, 62, 62, 58, 83, 31],
       [51, 45, 39,  2, 94, 85, 34, 23, 24, 30],
       [32, 47, 87, 62, 19, 17,  6, 33, 99, 34],
       [95, 63, 70,  8, 59, 18,  0, 11,  3, 61],
       [68, 87,  6,  3, 15, 61,  1, 46,  0, 50]])

In [65]:
arr2[::-1]

array([[68, 87,  6,  3, 15, 61,  1, 46,  0, 50],
       [95, 63, 70,  8, 59, 18,  0, 11,  3, 61],
       [32, 47, 87, 62, 19, 17,  6, 33, 99, 34],
       [51, 45, 39,  2, 94, 85, 34, 23, 24, 30],
       [80, 15, 98, 98, 35, 62, 62, 58, 83, 31],
       [ 3, 83, 38, 80, 76, 78, 49, 70, 28, 24],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43],
       [36, 76, 60, 50, 28, 39, 38, 22,  8, 41],
       [79, 31, 41, 43, 65, 39, 20, 39, 14, 97],
       [86, 98, 96, 64, 63, 96, 33, 76, 96, 31]])

In [66]:
arr2[::-2]

array([[68, 87,  6,  3, 15, 61,  1, 46,  0, 50],
       [32, 47, 87, 62, 19, 17,  6, 33, 99, 34],
       [80, 15, 98, 98, 35, 62, 62, 58, 83, 31],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43],
       [79, 31, 41, 43, 65, 39, 20, 39, 14, 97]])

In [67]:
arr2[::-3]

array([[68, 87,  6,  3, 15, 61,  1, 46,  0, 50],
       [51, 45, 39,  2, 94, 85, 34, 23, 24, 30],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43],
       [86, 98, 96, 64, 63, 96, 33, 76, 96, 31]])

In [68]:
arr2

array([[86, 98, 96, 64, 63, 96, 33, 76, 96, 31],
       [79, 31, 41, 43, 65, 39, 20, 39, 14, 97],
       [36, 76, 60, 50, 28, 39, 38, 22,  8, 41],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43],
       [ 3, 83, 38, 80, 76, 78, 49, 70, 28, 24],
       [80, 15, 98, 98, 35, 62, 62, 58, 83, 31],
       [51, 45, 39,  2, 94, 85, 34, 23, 24, 30],
       [32, 47, 87, 62, 19, 17,  6, 33, 99, 34],
       [95, 63, 70,  8, 59, 18,  0, 11,  3, 61],
       [68, 87,  6,  3, 15, 61,  1, 46,  0, 50]])

In [69]:
arr2[0:10:3]

array([[86, 98, 96, 64, 63, 96, 33, 76, 96, 31],
       [81, 64, 65, 73, 27, 43, 36, 83, 13, 43],
       [51, 45, 39,  2, 94, 85, 34, 23, 24, 30],
       [68, 87,  6,  3, 15, 61,  1, 46,  0, 50]])

In [70]:
arr2.max()

np.int64(99)

In [71]:
arr2.min()

np.int64(0)

In [72]:
arr2.mean()

np.float64(48.72)

In [73]:
#arr2.median()

In [74]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9,8])
median(a)

np.float64(3.5)

In [75]:
arr = np.array([0, 1, 2, 3, 4, 5])

In [76]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [77]:
arr.reshape(2,3,order='F') # print element with fortran (pahle 0 phir uske niche 1 phir 2 , means columns wise dekho )

array([[0, 2, 4],
       [1, 3, 5]])

In [78]:
# importing Numpy package
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

# **Indexing**

In [79]:
mat = np.arange(0,100).reshape(10,10)

In [80]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
row = 4
col = 5

In [82]:
col

5

In [83]:
row

4

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
mat[row,col]

np.int64(45)

In [86]:
mat[4,5]

np.int64(45)

In [87]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [88]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [89]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [90]:
mat[1:2,2:4]

array([[12, 13]])

In [91]:
mat[2:3,2:3]

array([[22]])

In [92]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

# **Masking**

In [94]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
print(mat > 50)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]


In [96]:
print(mat[mat==50] )

[50]


In [97]:
print(mat == 50)

[[False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]]


# **python program to generat otp**

In [98]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 5324
