# 1. Array Creation **Function**

In [1]:
import numpy as np

In [2]:
# create an array from a list
a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [3]:
# created an aray with evenly spaced values
b = np.arange(0,10,3)
print("Array b:",b)

Array b: [0 3 6 9]


In [4]:
d = np.zeros((2,3))
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d = np.zeros((2,3),dtype=int)
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [6]:
e = np.ones((3,2))
print("Array d:\n",e)

Array d:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
f = np.eye(4)  # 4*4 identity matrix
print("Array e:\n",f)

Array e:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. **Array Manipulation Function**

In [8]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Array is:\n",reshaped)

Array is:
 [[1 2 3]]


In [9]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1))
print("Array is:\n",reshaped)

Array is:
 [[1]
 [2]
 [3]]


In [10]:
# Flatten array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1)
print(flattened)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# transpose
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print(transposed)

[[1 3]
 [2 4]]


In [12]:
# stack array vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print(stacked)

[[1 2]
 [3 4]]


In [13]:
# stack array vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print(stacked)

[1 2 3 4]


# **3. Mathematical Function**

In [14]:
# add to array
g = np.array([1,2,3,4])
added = np.add(g,2)
print(added)

[3 4 5 6]


In [15]:
# square each
squared = np.power(g,2)
print(squared)

[ 1  4  9 16]


In [16]:
# Square root of each element
sqrt_val = np.sqrt(g)
print(sqrt_val)

[1.         1.41421356 1.73205081 2.        ]


In [17]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [18]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [19]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,a1)
print(dot_product)

14


# **4. Statistic Functions**

In [20]:
s = np.array([1,2,3,4])
means = np.mean(s)
print(means)

2.5


In [21]:
vari = np.var(s)
print(vari)

1.25


In [22]:
std_dev = np.std(s)
print(std_dev)

1.118033988749895


In [23]:
s

array([1, 2, 3, 4])

In [24]:
print(np.min(s))

1


In [25]:
print(np.max(s))

4


# **5. Random sampling Function**

In [26]:
random_vals = np.random.rand(3)
print(random_vals)

[0.63956561 0.68310789 0.88231084]


In [27]:
np.random.seed(0)
random_vals = np.random.rand(3)
print(random_vals)

[0.5488135  0.71518937 0.60276338]


In [28]:
rand_ints = np.random.randint(1,5,size=4)
print(rand_ints)

[4 4 2 4]


In [29]:
np.random.seed(0)

rand_int = np.random.randint(0,10,size=5)
print(rand_int)

[5 0 3 3 7]


In [30]:
#np.random.seed(0)

rand_int = np.random.randint(0,10,size=5)
print(rand_int)

[9 3 5 2 4]


# **6. Boolean & Logical Functions**

In [31]:
# Check if all elements are True
# all
logical_test = np.array([True , False ,True])
all_true = np.all(logical_test)
print(all_true)

False


In [32]:
# Check if all elements are True
# all
logical_test = np.array([True , True ,True])
all_true = np.all(logical_test)
print(all_true)

True


In [33]:
# Check if all elements are True
# all
logical_test = np.array([False , False ,False])
all_true = np.all(logical_test)
print(all_true)

False


# **7. Set Operations**

In [34]:
# intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a,set_b)
print(intersection)

[3 4]


In [35]:
union = np.union1d(set_a,set_b)
print(union)

[1 2 3 4 5 6]


# **9. Array Attribute Functions**

In [36]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64
